version: '3.8'
services:
  cleartax_nodejs:
    build: .
    container_name: cleartax_nodejs
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      cleartax_postgres:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}        
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}        

  cleartax_postgres:
    image: postgres:15
    container_name: cleartax_postgres
    environment:
      POSTGRES_USER: ${DB_USER}        
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}          
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: cleartax_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - cleartax_postgres
    network_mode: bridge
    extra_hosts:
      - "cleartax_postgres:host-gateway"

volumes:
  postgres_data: