version: '3.8'

services:
  cleartax_nodejs:  # Node.js Backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: cleartax_nodejs
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      cleartax_postgres:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  cleartax_react:  # React Frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cleartax_react
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # For file watching in Docker
    stdin_open: true  # Enable interactive mode
    tty: true        # Allocate pseudo-TTY
    depends_on:
      - cleartax_nodejs

  cleartax_postgres:  # PostgreSQL Database
    image: postgres:15
    container_name: cleartax_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  cleartax_pgadmin:  # PGAdmin Web Interface
    image: dpage/pgadmin4
    container_name: cleartax_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - cleartax_postgres
    extra_hosts:
      - "cleartax_postgres:host-gateway"

volumes:
  postgres_data: