services:
  cleartax_nodejs:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: cleartax_nodejs
    ports:
      - "3001:3000"
    volumes:
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
      - ./.env:/app/.env
    command: node --watch --experimental-strip-types --env-file=./.env src/index.ts
    depends_on:
      immudb:
        condition: service_started
    environment:
      - IMMUDB_HOST=immudb
      - IMMUDB_PORT=3322
      - IMMUDB_USER=immudb
      - IMMUDB_PASSWORD=immudb
      - JWT_SECRET=${JWT_SECRET}

  cleartax_react:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    container_name: cleartax_react
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true
    depends_on:
      - cleartax_nodejs

  immudb:
    image: codenotary/immudb:latest
    container_name: cleartax_immudb
    ports:
      - "3322:3322"
      - "8081:8080"
    volumes:
      - immudb_data:/var/lib/immudb
    restart: always
  
  minio:
    image: quay.io/minio/minio
    container_name: cleartax_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    restart: always

volumes:
  immudb_data:
  minio_data:
