services:
  cleartax_nodejs:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: cleartax_nodejs
    ports:
      - "3001:3000"
    volumes:
      - ./server/src:/app/src
      - ./server/package.json:/app/package.json
      - ./.env:/app/.env
    command: node --watch --experimental-strip-types --env-file=./.env src/index.ts
    depends_on:
      immudb:
        condition: service_started
    environment:
      - IMMUDB_HOST=immudb
      - IMMUDB_PORT=3322
      - IMMUDB_USER=immudb
      - IMMUDB_PASSWORD=immudb
      - JWT_SECRET=${JWT_SECRET}

  cleartax_react:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cleartax_react
    ports:
      - "3002:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - cleartax_nodejs

  immudb:
    image: codenotary/immudb:latest
    container_name: cleartax_immudb
    ports:
      - "3322:3322"
      - "8080:8080"
    volumes:
      - immudb_data:/var/lib/immudb
    restart: always

volumes:
  immudb_data:
