name: Deploy to nikolabadjevic.com
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: FTP_SERVER
    steps:
      - uses: actions/checkout@v4

      - name: Install and Build React App
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Verify Build Output
        working-directory: ./client
        run: ls -la build/

      - name: Deploy to nikolabadjevic.com
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./client/build/
          server-dir: /public_html/cleartax/
          protocol: ftps
          dangerous-clean-slate: true